### ISSUE TITLE
Look into the possibility of not converting everything / anything 

### ISSUE THREAD

**Issue by BjoernPetersen** [BjoernPetersen/MusicBot#105]
- (If I'm not mistaken) PyAudio can play anything PyDub can convert
- mp3-Tags are not really needed if the meta information for offline playlists is stored in a database anyway, which is arguably the more sensible approach anyway
- songs added from the hard drive are not converted anyway
- conversion more than doubles the time for loading a song, which impairs user experience
  <br/>
  <br/>
  <br/>
  Downsides:
- keeping files in the format it is downloaded in possibly increases needed disk space

**Comment by BjoernPetersen** [comment]
In my opinion, the upsides definitely outweigh the downsides here

**Comment by BjoernPetersen** [comment]
@FelixGail what's your opinion on this?

**Comment by FelixGail** [comment]
I agree to your point of converting the files.

Some thoughts on your arguments:
> keeping files in the format it is downloaded in possibly increases needed disk space

most of the songs are taken from play music and are therefore in .mp3-format anyway. 
<br>
> mp3-Tags are not really needed if the meta information for offline playlists is stored in a database anyway, which is arguably the more sensible approach anyway

 i agree that using a database to keep the song information is the best approach for a running bot, but i would store mp3-tags for all songs in mp3 format anyway for multiple reasons.
 1. if the database is lost or corrupted the song information is not lost
 2. Importing offline songs will require mp3-tag handling anyway since it is the best way to garther song information and saving them allows to (re)import them later or on another bot
 3. It is possible to use the songs in any media player (except groove maybe)

**Comment by BjoernPetersen** [comment]
> most of the songs are taken from play music and are therefore in .mp3-format anyway

yup, I would also argue that disk space isn't a big concern nowadays anyway

> Importing offline songs will require mp3-tag handling anyway since it is the best way to garther song information and saving them allows to (re)import them later or on another bot

Of course mp3-tags need to be read for that. But I would argue that only the playlist_manager.py needs to handle those tags and stores the information in the database.
Songs imported from the hard disk are not and should not be modified, moved or copied, so they aren't relevant for the question of saving meta-information of songs to their mp3-tags anyway.

> It is possible to use the songs in any media player (except groove maybe)

I'm not sure how much we should endorse that. It circumvents Google Play Music's download limit for uploaded songs, and even enables downloading songs normally only streamable.
Legally the Play Music usage is questionable anyway, but that's kinda crossing a line for me...

> if the database is lost or corrupted the song information is not lost

While that is technically correct, it's actually not an issue:
* For songs from web-services (in online mode)
  * the information is not stored in the database (only in-memory)
  * we get the song information when the song is returned with search results or suggestions, so we never need to look up the information out of thin air
* For songs in offline playlists
  * if the database is lost, we won't have a reason to look up song info **for songs from the database**, do we? (we 'don't know' about the songs existence without the database)

**Comment by FelixGail** [comment]
When not saving id3 tags it is not possible to import the songs from
another bot or after corruption, which would render all downloaded data
useless.

Which is not that big of a deal after thinking about it again while the
legality issue seems way bigger.

Not saving the tags is probably the better solution.

**Comment by BjoernPetersen** [comment]
Importing a database with local (from hard disk) songs from another bot would also be very problematic, because the songs are not stored in the same directory as the downloaded songs.
