### ISSUE TITLE
Create installer scripts for Windows and Linux

### ISSUE THREAD

**Issue by BjoernPetersen** [BjoernPetersen/MusicBot#115]

**Comment by FelixGail** [comment]
isn't this difficult with linux systems using pip3 instead of pip partly?

**Comment by BjoernPetersen** [comment]
That could be difficult. Maybe making the Linux installation script a python script would help

**Comment by BjoernPetersen** [comment]
On Windows, however, a batch-script is probably the better solution, since python usually isn't installed beforehand.
