### ISSUE TITLE
Use a compressed file format

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/MusicBot#74]
Is there a reason the music files are saved in .wav-format?
Not only does this take a lot of disk-space, using mp3 would also allow using id3-tags

**Comment by BjoernPetersen** [comment]
- It is absolutely possible to add id3-tags to .wav files
- I agree with the disk-space issue, but unfortunately the simpleaudio library doesn't support the mp3-format
  - However, the hunt for a replacement is on: #75
