### ISSUE TITLE
Find a better python 3 audio player library

### ISSUE THREAD

**Issue by BjoernPetersen** [BjoernPetersen/MusicBot#75]
Currently [simpleaudio](http://simpleaudio.readthedocs.io/en/latest/) is used, because it is almost dependency free, supports a lot of platforms and is easy to use.

**Unfortunately, simpleaudio lacks (most importantly):**
- mp3 support
- support for pausing

### A replacement library should be reasonably easy to install and meet the following requirements:
1. Python 3.5+ support
1. Windows and Linux/ALSA support
1. fully functional in command line (unlike most "gaming" libraries that need an open window / OpenGL context)
1. support for any compressed file format [pydub](http://pydub.com/) supports (basically anything ffmpeg supports)
  1. the file format should support ID3-Tags
1. support for pausing and/or saving the current position in a song and starting the song from that position again later

### Candidates:
Feel free to add suggestions and test some
- ~~pygame~~ (needs OpenGL context)
- ~~pyglet~~ (not working in command-line-only mode, see requirement 3)
- ~~Snack~~ (dead)
- ~~winsound~~ (Windows-only)
- ~~[sound4python](https://github.com/standarddeviant/sound4python)~~
- pyaudio
- pymedia
- (_something, something ffmpeg_)
- pydub ([already a dependency, seems to require pyaudio](https://github.com/jiaaro/pydub/blob/master/pydub/playback.py))

If finding such a library turns out to be impossible, maybe someone should wrap some platform-dependent libraries to create a new, platform-independent one.

**Comment by BjoernPetersen** [comment]
Currently looking into a possible solution using PyAudio and possibly pydub in combination with ffmpeg

**Comment by FelixGail** [comment]
I don't recommend using sound4pyton for multiple reasons:
- no mp3-support
- dependencies: sox
- unnamed python dependencies: e.g. numpy
- has to be installed manually (with setup.py)

**Comment by BjoernPetersen** [comment]
PyAudio is working, this issue will be closed automatically when the changes are merged into the master branch. Before I do that I'll have to perform some additional testing and some changes to the playlist_manager.py though.

The dev version of the bot inlcludes:
- actual playback pausing
- mp3 support
- metadata for mp3s
- an offline music API
  - currently only enabled in offline mode (--offline)
  - limited to downloaded songs
  - only accessible via REST API (obviously)
  - playlist support
- known issues
  - normalization is deactivated
  - the active offline API playlist can't be controlled via any interface yet
