### ISSUE TITLE
Playlist Download Error

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/MusicBot#98]
Error while trying to download a playlist

Traceback:
```
Loading song Bon Jovi - It's My Life (03:44)
Exception during download of Twfdk2zxnruswyxwdhuqswgnaau
Traceback (most recent call last):
  File "/media/***/MusicBot/musicbot/music_apis.py", line 611, in _download
    with open(native_fname_tmp, "wb") as file:
OSError: [Errno 5] Input/output error: 'songs/native_Twfdk2zxnruswyxwdhuqswgnaau.mp3.tmp'
Exception during download of Twfdk2zxnruswyxwdhuqswgnaau
Traceback (most recent call last):
  File "/media/***/MusicBot/musicbot/music_apis.py", line 134, in load
    native_fname = self.api._download(self)
  File "/media/***/MusicBot/musicbot/music_apis.py", line 615, in _download
    raise e
  File "/media/***/MusicBot/musicbot/music_apis.py", line 611, in _download
    with open(native_fname_tmp, "wb") as file:
OSError: [Errno 5] Input/output error: 'songs/native_Twfdk2zxnruswyxwdhuqswgnaau.mp3.tmp'
```

Same Error for every song in playlist.

**Comment by BjoernPetersen** [comment]
I guess it's time to end this 2-week pause

**Comment by BjoernPetersen** [comment]
GMusic playlist download is working on Windows. What Ubuntu / Python versions are you using?

**Comment by FelixGail** [comment]
python 3.5.2

**Comment by BjoernPetersen** [comment]
OK, I'll try to recreate the issue

**Comment by BjoernPetersen** [comment]
Works for me under Ubuntu 16.10, too. Did you change anything in the config.json?

**Comment by BjoernPetersen** [comment]
Also:
* what path are you saving songs to, a hard disk? 
* are you able to create files and write into them in that directoy?

**Comment by FelixGail** [comment]
Into the default songs directory.
I am able to create and delete files, i will try to set chmod to 777 and try again

**Comment by FelixGail** [comment]
I am awfully sorry. While providing me with the share token, play music did not share the playlist

**Comment by BjoernPetersen** [comment]
That seems unlikely as the cause of this error for a number of reasons:
1. Playlists don't need to be shared to download them with the playlist_manager (as long as it's your playlist)
2. The error occurred while downloading a song from the playlist, the log contains the name and storeId of the song. This indicates that there was no error loading what songs are in the playlists.
3. The error was an OSError with error code 5 while creating or writing to the song file on your disk. **Almost all results of my search for causes of this error were hardware issues.**
